### ISSUE TITLE
Branch not synced between Github and Gitolite

### ISSUE THREAD

**Issue by damien-list** [RalfJung/git-mirror#1] opened 2017-03-10 12:29 UTC
Hi,

When I decide to delete a branch in Github, it is not synced with our Gitolite instance.
Maybe I'm missing something when setting up your script.

Thanks for your help

**Comment by RalfJung** [comment] 2017-03-10 16:43
I seem to remember testing that... strange. How did you delete the branch? A `git push origin :branch` to GitHub, or in the Web UI? Could you go to the Webhook configuration and look for the event triggered when you deleted the branch, and post here in the bug both the request sent to the webhook as well as the response from the webhook?

**Comment by damien-list** [comment] 2017-03-10 17:18
I delete branch from the Web UI.

Here the payload :
```
{
  "ref": "refs/heads/3266_template_remove_visual_error",
  "before": "d466d6863d86a6bb6a7b9c06611295341709e96d",
  "after": "0000000000000000000000000000000000000000",
  "created": false,
  "deleted": true,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/Vertical-Mail/selfmail/compare/d466d6863d86...000000000000",
  "commits": [

  ],
  "head_commit": null,
  "repository": {
    "id": 82929596,
    "name": "selfmail",
    "full_name": "Vertical-Mail/selfmail",
    "owner": {
      "name": "Vertical-Mail",
      "email": null,
      "login": "Vertical-Mail",
      "id": 25981996,
      "avatar_url": "https://avatars1.githubusercontent.com/u/25981996?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Vertical-Mail",
      "html_url": "https://github.com/Vertical-Mail",
      "followers_url": "https://api.github.com/users/Vertical-Mail/followers",
      "following_url": "https://api.github.com/users/Vertical-Mail/following{/other_user}",
      "gists_url": "https://api.github.com/users/Vertical-Mail/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Vertical-Mail/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Vertical-Mail/subscriptions",
      "organizations_url": "https://api.github.com/users/Vertical-Mail/orgs",
      "repos_url": "https://api.github.com/users/Vertical-Mail/repos",
      "events_url": "https://api.github.com/users/Vertical-Mail/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Vertical-Mail/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": true,
    "html_url": "https://github.com/Vertical-Mail/selfmail",
    "description": "Selfmail is a SaaS Marketing Platform.",
    "fork": false,
    "url": "https://github.com/Vertical-Mail/selfmail",
    "forks_url": "https://api.github.com/repos/Vertical-Mail/selfmail/forks",
    "keys_url": "https://api.github.com/repos/Vertical-Mail/selfmail/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Vertical-Mail/selfmail/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Vertical-Mail/selfmail/teams",
    "hooks_url": "https://api.github.com/repos/Vertical-Mail/selfmail/hooks",
    "issue_events_url": "https://api.github.com/repos/Vertical-Mail/selfmail/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Vertical-Mail/selfmail/events",
    "assignees_url": "https://api.github.com/repos/Vertical-Mail/selfmail/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Vertical-Mail/selfmail/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Vertical-Mail/selfmail/tags",
    "blobs_url": "https://api.github.com/repos/Vertical-Mail/selfmail/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Vertical-Mail/selfmail/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Vertical-Mail/selfmail/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Vertical-Mail/selfmail/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Vertical-Mail/selfmail/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Vertical-Mail/selfmail/languages",
    "stargazers_url": "https://api.github.com/repos/Vertical-Mail/selfmail/stargazers",
    "contributors_url": "https://api.github.com/repos/Vertical-Mail/selfmail/contributors",
    "subscribers_url": "https://api.github.com/repos/Vertical-Mail/selfmail/subscribers",
    "subscription_url": "https://api.github.com/repos/Vertical-Mail/selfmail/subscription",
    "commits_url": "https://api.github.com/repos/Vertical-Mail/selfmail/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Vertical-Mail/selfmail/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Vertical-Mail/selfmail/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Vertical-Mail/selfmail/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Vertical-Mail/selfmail/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Vertical-Mail/selfmail/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Vertical-Mail/selfmail/merges",
    "archive_url": "https://api.github.com/repos/Vertical-Mail/selfmail/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Vertical-Mail/selfmail/downloads",
    "issues_url": "https://api.github.com/repos/Vertical-Mail/selfmail/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Vertical-Mail/selfmail/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Vertical-Mail/selfmail/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Vertical-Mail/selfmail/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Vertical-Mail/selfmail/labels{/name}",
    "releases_url": "https://api.github.com/repos/Vertical-Mail/selfmail/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Vertical-Mail/selfmail/deployments",
    "created_at": 1487856318,
    "updated_at": "2017-02-24T16:54:11Z",
    "pushed_at": 1489166065,
    "git_url": "git://github.com/Vertical-Mail/selfmail.git",
    "ssh_url": "git@github.com:Vertical-Mail/selfmail.git",
    "clone_url": "https://github.com/Vertical-Mail/selfmail.git",
    "svn_url": "https://github.com/Vertical-Mail/selfmail",
    "homepage": null,
    "size": 187508,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "HTML",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 3,
    "forks": 0,
    "open_issues": 3,
    "watchers": 1,
    "default_branch": "master",
    "stargazers": 1,
    "master_branch": "master",
    "organization": "Vertical-Mail"
  },
  "pusher": {
    "name": "damien-list",
    "email": "damien-list@users.noreply.github.com"
  },
  "organization": {
    "login": "Vertical-Mail",
    "id": 25981996,
    "url": "https://api.github.com/orgs/Vertical-Mail",
    "repos_url": "https://api.github.com/orgs/Vertical-Mail/repos",
    "events_url": "https://api.github.com/orgs/Vertical-Mail/events",
    "hooks_url": "https://api.github.com/orgs/Vertical-Mail/hooks",
    "issues_url": "https://api.github.com/orgs/Vertical-Mail/issues",
    "members_url": "https://api.github.com/orgs/Vertical-Mail/members{/member}",
    "public_members_url": "https://api.github.com/orgs/Vertical-Mail/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/25981996?v=3",
    "description": null
  },
  "sender": {
    "login": "damien-list",
    "id": 1785580,
    "avatar_url": "https://avatars3.githubusercontent.com/u/1785580?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/damien-list",
    "html_url": "https://github.com/damien-list",
    "followers_url": "https://api.github.com/users/damien-list/followers",
    "following_url": "https://api.github.com/users/damien-list/following{/other_user}",
    "gists_url": "https://api.github.com/users/damien-list/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/damien-list/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/damien-list/subscriptions",
    "organizations_url": "https://api.github.com/users/damien-list/orgs",
    "repos_url": "https://api.github.com/users/damien-list/repos",
    "events_url": "https://api.github.com/users/damien-list/events{/privacy}",
    "received_events_url": "https://api.github.com/users/damien-list/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

Here the body of the response :

```
Updated selfmail:refs/heads/3266_template_remove_visual_error from mirror github from d466d6863d86a6bb6a7b9c06611295341709e96d to 0000000000000000000000000000000000000000
hooks/post-receive: 9: hooks/post-receive: die: not found
Everything up-to-date
```

**Comment by damien-list** [comment] 2017-03-24 10:24
It seems to come from : 

`Updated selfmail:refs/heads/3266_template_remove_visual_error from mirror github from d466d6863d86a6bb6a7b9c06611295341709e96d to 0000000000000000000000000000000000000000
hooks/post-receive: 9: hooks/post-receive: die: not found`

Have you any idea ?

**Comment by RalfJung** [comment] 2017-03-27 16:48
> I delete branch from the Web UI.

Indeed I never tested that one; I guess I did not expect it to make any difference compared to deleted via `git push origin :branch`.

**Comment by RalfJung** [comment] 2017-03-27 16:52
The second line of that error however refers to the `post-receive` file managed by Gitolite. That's strange.

Also, I just tried deleting via the webinterface, and things worked just fine. The output is
```
Updated git-mirror:refs/heads/test from mirror github from 91149b3b918cfe8d95e261ad8ce7607606e98ba3 to 0000000000000000000000000000000000000000
```

**Comment by RalfJung** [comment] 2017-03-27 16:58
Okay, so the error is triggered when git-mirror calls the post-receive hooks on the local side. What is the content of `hooks/post-receive` in the repository in question on the Gitolite side (i.e., on the server that executes the webhooks)? It should be something like
```
#/bin/sh

# Determine what input the hook needs
# post-update takes args, pre/post-receive take stdin
type=args
stdin=''
[ $0 != hooks/post-update ] && {
    type=stdin
    stdin=`cat`
}

for h in $0.*; do
    [ -x $h ] || continue
    if [ $type = args ]
    then
        $h $@
    else
        echo "$stdin" | $h
    fi
done
```

Also, that error really looks like it should occur on every Github-synced trigger; does pushing to Github work correctly for you?

I guess one thing I could do is trying to execute the hook directly, rather than running it in the shell. No idea why I did this back then...

**Comment by RalfJung** [comment] 2017-03-27 17:07
All right, I changed it to not assume the interpreter to be bash. However, all released versions of Gitolite actually put a broken file there (the first line is `#/bin/sh` instead of `#!/bin/sh`), so I am not sure if this is a good idea...
Does this change help for you (after fixing the shebang, potentially)?

**Comment by damien-list** [comment] 2017-03-28 19:41
Hi,

I've changed the `hooks/post-receive` to reflect what you've put in your previous answer (with the shebang). I have no more the error but the branch still appears in gitolite if I do a git branch -r.

Maybe something I'm missing ?

**Comment by damien-list** [comment] 2017-03-28 19:55
I've tried the other way, I've deleted a branch on gitolite with `git branch -d -r origin/mybranchname` and It still appears on github.

**Comment by RalfJung** [comment] 2017-03-28 21:14
`git fetch` will not notice when remote branches are deleted, you have to do `git fetch --prune`.
I was assuming you are using the webinterface to check which branches still exist...

**Comment by damien-list** [comment] 2017-03-29 07:36
I'm checking both ways.
When I delete a branch from github, I don't see it deleted when I do a `git branch -r` on gitolite.
When I delete a branch from gitolile with `git branch -d -r origin/mybranchname`, I still see the branch on github.

**Comment by RalfJung** [comment] 2017-03-29 13:51
Before you do the `git branch -r`, could you please do a `git fetch --prune <name-of-the-remote>`?
After all, even if the branch is properly deleted from GitHub, your local git clone still has to learn that this is the case.

Also, for the case of you deleting the branch in gitolite, could you please go to the GitHub web interface and see if the branch is still there? If `git branch -r` lists the branch but GitHub doesn't, the problem is actually that you didn't do `git fetch --prune`.

**Comment by RalfJung** [comment] 2017-03-29 13:59
> When I delete a branch from gitolile with git branch -d -r origin/mybranchname, I still see the branch on github.

Notice that `git branch -d -r` does *not* delete the branch on the server, it just deletes your local copy of the server's branch. So it is absolutely normal that this is not synced to the other side.
To delete branch "mybranchname" on the server identified by remote "origin", do `git push origin :mybranchname`.

Could you reproduce the error without using the browser (just git commands), give the exact sequence of commands you are executing, and what they output?

**Comment by damien-list** [comment] 2017-03-29 14:28
> When I delete a branch from gitolile with git branch -d -r origin/mybranchname, I still see the branch on github.

was answered with : 

> Notice that `git branch -d -r` does not delete the branch on the server, it just deletes your local copy of the server's branch. So it is absolutely normal that this is not synced to the other side.
To delete branch "mybranchname" on the server identified by remote "origin", do `git push origin :mybranchname`.

And When I delete a branch from github, I don't see it deleted when I do a `git branch -r` on gitolite.

was answered with : 

> Before you do the `git branch -r`, could you please do a `git fetch --prune <name-of-the-remote>`?
After all, even if the branch is properly deleted from GitHub, your local git clone still has to learn that this is the case.

Sorry to have bother you with my lack of git knowledge...

**Comment by RalfJung** [comment] 2017-03-29 15:45
That's fine :)

I'll close this issue then.

**Closed as completed by RalfJung** 2017-03-29 15:45 UTC
